export const SCREENING_QUESTIONS_TEXT_AREA_ROWS = 3;
export const SCREENING_QUESTIONS_TEXT_AREA_EN_MAX_WORDS = 200;
export const SCREENING_QUESTIONS_TEXT_AREA_FR_MAX_WORDS = 266;
export const SCREENING_QUESTIONS_MAX_QUESTIONS = 3;

export const ASSESSMENT_STEPS_FEW_STEPS = 1;
export const ASSESSMENT_STEPS_MANY_STEPS = 4;
export const ASSESSMENT_STEPS_MAX_STEPS = 6;
