codecov:
  branch: main
  coverage:
    status:
      project:
        default:
          target: auto
          threshold: 100%
        jest:
          target: auto
          threshold: 100%
        phpunit:
          target: auto
          threshold: 100%
    after_n_builds: 1
    require_ci_to_pass: false
    changes: false
    diff: false
    base: auto
    if_changed: false
    comment:
      layout: "header, diff, folders, files"
      behavior: default
      head: true
      body: true
      footer: true
    checks:
      after_n_builds: 1
      changes: false
      diff: false
      if_changed: false


