services:

  postgres:
    image: postgres:12.11
    restart: always
    environment:
      POSTGRES_PASSWORD: password1234
    volumes:
      - ./infrastructure/db:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  webserver:
    # All images: https://mcr.microsoft.com/v2/appsvc/php/tags/list
    image: mcr.microsoft.com/appsvc/php:7.4-fpm-xdebug_20220609.1.tuxprod
    ports:
      - 8000:80
      - 8001:443
    volumes:
      - ./:/home/site/wwwroot
    # Uncomment env_file if you want to simulate environment variables in the app service
    # env_file:
    #  - ./infrastructure/conf/.webserver_env
    command: ./infrastructure/bin/post_deployment.sh .

volumes:
  pgdata:
  maintenancedata:
