packages:
  - apps/*
  - packages/*
allowBuilds:
  "@parcel/watcher": true
  "@tailwindcss/oxide": true
  esbuild: true
  unrs-resolver: true
autoInstallPeers: true
nodeLinker: hoisted
ignoreWorkspaceRootCheck: true
