import { AllUsersQuery, Language } from "../api/generated";

export default (): AllUsersQuery["users"] => [
  {
    id: 1,
    firstName: "Maura",
    lastName: "Attow",
    email: "mattow0@ning.com",
    telephone: "+86 736 537 3244",
    preferredLang: Language.En,
  },
  {
    id: 2,
    firstName: "Maegan",
    lastName: "Deeny",
    email: "mdeeny1@oaic.gov.au",
    telephone: "+56 335 450 9374",
    preferredLang: Language.Fr,
  },
  {
    id: 3,
    firstName: "Priscilla",
    lastName: "Selbie",
    email: "pselbie2@mail.ru",
    telephone: "+63 728 418 8694",
    preferredLang: Language.En,
  },
  {
    id: 4,
    firstName: "Gannie",
    lastName: "Oakwell",
    email: "goakwell3@netvibes.com",
    telephone: "+46 682 241 9721",
    preferredLang: Language.Fr,
  },
  {
    id: 5,
    firstName: "Harvey",
    lastName: "Elleyne",
    email: "helleyne4@ftc.gov",
    telephone: "+54 171 482 5542",
    preferredLang: Language.Fr,
  },
  {
    id: 6,
    firstName: "Zia",
    lastName: "By",
    email: "zby5@booking.com",
    telephone: "+62 106 582 6328",
    preferredLang: Language.Fr,
  },
  {
    id: 7,
    firstName: "Sondra",
    lastName: "Barnes",
    email: "sbarnes6@howstuffworks.com",
    telephone: "+62 785 598 2154",
    preferredLang: Language.Fr,
  },
  {
    id: 8,
    firstName: "Glen",
    lastName: "Lawden",
    email: "glawden7@cpanel.net",
    telephone: "+234 972 695 7224",
    preferredLang: Language.Fr,
  },
  {
    id: 9,
    firstName: "Barret",
    lastName: "Moody",
    email: "bmoody8@businessweek.com",
    telephone: "+420 972 891 9527",
    preferredLang: Language.Fr,
  },
  {
    id: 10,
    firstName: "Eward",
    lastName: "Silvers",
    email: "esilvers9@skype.com",
    telephone: "+46 723 772 1214",
    preferredLang: Language.Fr,
  },
  {
    id: 11,
    firstName: "Aili",
    lastName: "Aasaf",
    email: "aaasafa@shinystat.com",
    telephone: "+967 746 353 9448",
    preferredLang: Language.Fr,
  },
  {
    id: 12,
    firstName: "Marika",
    lastName: "Clayhill",
    email: "mclayhillb@google.pl",
    telephone: "+598 693 672 0951",
    preferredLang: Language.Fr,
  },
  {
    id: 13,
    firstName: "Corrie",
    lastName: "MacBrearty",
    email: "cmacbreartyc@networkadvertising.org",
    telephone: "+63 111 946 0943",
    preferredLang: Language.Fr,
  },
  {
    id: 14,
    firstName: "Marylinda",
    lastName: "Giffin",
    email: "mgiffind@weebly.com",
    telephone: "+375 732 435 9600",
    preferredLang: Language.Fr,
  },
  {
    id: 15,
    firstName: "Darlene",
    lastName: "McCheyne",
    email: "dmccheynee@zimbio.com",
    telephone: "+244 811 341 7490",
    preferredLang: Language.Fr,
  },
  {
    id: 16,
    firstName: "Betta",
    lastName: "Imison",
    email: "bimisonf@sogou.com",
    telephone: "+86 538 355 4462",
    preferredLang: Language.Fr,
  },
  {
    id: 17,
    firstName: "Kennan",
    lastName: "Vasyagin",
    email: "kvasyaging@auda.org.au",
    telephone: "+63 615 456 5832",
    preferredLang: Language.Fr,
  },
  {
    id: 18,
    firstName: "Nelie",
    lastName: "Newbury",
    email: "nnewburyh@eventbrite.com",
    telephone: "+255 295 455 4273",
    preferredLang: Language.Fr,
  },
  {
    id: 19,
    firstName: "Burnard",
    lastName: "Clother",
    email: "bclotheri@harvard.edu",
    telephone: "+7 378 450 8774",
    preferredLang: Language.Fr,
  },
  {
    id: 20,
    firstName: "Elena",
    lastName: "Gerrans",
    email: "egerransj@phpbb.com",
    telephone: "+970 982 430 5033",
    preferredLang: Language.Fr,
  },
  {
    id: 21,
    firstName: "Slade",
    lastName: "Kilvington",
    email: "skilvingtonk@about.com",
    telephone: "+86 644 543 1110",
    preferredLang: Language.Fr,
  },
  {
    id: 22,
    firstName: "Shirleen",
    lastName: "Maude",
    email: "smaudel@xinhuanet.com",
    telephone: "+54 488 702 2108",
    preferredLang: Language.Fr,
  },
  {
    id: 23,
    firstName: "Mercie",
    lastName: "Plowes",
    email: "mplowesm@arstechnica.com",
    telephone: "+1 702 275 5062",
    preferredLang: Language.Fr,
  },
  {
    id: 24,
    firstName: "Jacinda",
    lastName: "Astall",
    email: "jastalln@google.com.hk",
    telephone: "+46 890 822 6619",
    preferredLang: Language.Fr,
  },
  {
    id: 25,
    firstName: "Fionnula",
    lastName: "Eggers",
    email: "feggerso@diigo.com",
    telephone: "+86 100 905 3005",
    preferredLang: Language.Fr,
  },
  {
    id: 26,
    firstName: "Evaleen",
    lastName: "Lonnon",
    email: "elonnonp@twitpic.com",
    telephone: "+33 991 115 6686",
    preferredLang: Language.Fr,
  },
  {
    id: 27,
    firstName: "Matti",
    lastName: "Ogdahl",
    email: "mogdahlq@webeden.co.uk",
    telephone: "+1 542 383 2118",
    preferredLang: Language.Fr,
  },
  {
    id: 28,
    firstName: "Maddie",
    lastName: "Liversage",
    email: "mliversager@psu.edu",
    telephone: "+351 746 955 9163",
    preferredLang: Language.Fr,
  },
  {
    id: 29,
    firstName: "Alissa",
    lastName: "De Robertis",
    email: "aderobertiss@washington.edu",
    telephone: "+7 635 297 0132",
    preferredLang: Language.Fr,
  },
  {
    id: 30,
    firstName: "Jackelyn",
    lastName: "Kubach",
    email: "jkubacht@posterous.com",
    telephone: "+234 268 864 1661",
    preferredLang: Language.Fr,
  },
  {
    id: 31,
    firstName: "Alphonse",
    lastName: "Benettolo",
    email: "abenettolou@oracle.com",
    telephone: "+7 298 249 9134",
    preferredLang: Language.Fr,
  },
  {
    id: 32,
    firstName: "Zelig",
    lastName: "Molian",
    email: "zmolianv@blogs.com",
    telephone: "+225 793 944 6866",
    preferredLang: Language.Fr,
  },
  {
    id: 33,
    firstName: "Inesita",
    lastName: "Baise",
    email: "ibaisew@timesonline.co.uk",
    telephone: "+359 564 810 3767",
    preferredLang: Language.Fr,
  },
  {
    id: 34,
    firstName: "Wanids",
    lastName: "Peachment",
    email: "wpeachmentx@hp.com",
    telephone: "+33 556 837 4542",
    preferredLang: Language.Fr,
  },
  {
    id: 35,
    firstName: "Germaine",
    lastName: "Covill",
    email: "gcovilly@quantcast.com",
    telephone: "+86 378 502 9116",
    preferredLang: Language.Fr,
  },
  {
    id: 36,
    firstName: "Sarena",
    lastName: "Najafian",
    email: "snajafianz@people.com.cn",
    telephone: "+420 986 703 7689",
    preferredLang: Language.Fr,
  },
  {
    id: 37,
    firstName: "Elton",
    lastName: "Matteini",
    email: "ematteini10@stumbleupon.com",
    telephone: "+1 212 509 7652",
    preferredLang: Language.Fr,
  },
  {
    id: 38,
    firstName: "Blanch",
    lastName: "Emig",
    email: "bemig11@cnet.com",
    telephone: "+51 427 466 8377",
    preferredLang: Language.Fr,
  },
  {
    id: 39,
    firstName: "Valeria",
    lastName: "Varren",
    email: "vvarren12@washington.edu",
    telephone: "+62 514 319 5820",
    preferredLang: Language.Fr,
  },
  {
    id: 40,
    firstName: "Dori",
    lastName: "Penchen",
    email: "dpenchen13@home.pl",
    telephone: "+1 858 184 5173",
    preferredLang: Language.Fr,
  },
  {
    id: 41,
    firstName: "Buddie",
    lastName: "MacCaffery",
    email: "bmaccaffery14@simplemachines.org",
    telephone: "+98 881 176 5240",
    preferredLang: Language.Fr,
  },
  {
    id: 42,
    firstName: "Dylan",
    lastName: "Zmitruk",
    email: "dzmitruk15@wikimedia.org",
    telephone: "+86 410 656 9238",
    preferredLang: Language.Fr,
  },
  {
    id: 43,
    firstName: "Gianina",
    lastName: "Pynn",
    email: "gpynn16@issuu.com",
    telephone: "+66 331 521 0182",
    preferredLang: Language.Fr,
  },
  {
    id: 44,
    firstName: "Hedy",
    lastName: "Keable",
    email: "hkeable17@google.cn",
    telephone: "+359 398 101 7735",
    preferredLang: Language.Fr,
  },
  {
    id: 45,
    firstName: "Davy",
    lastName: "O'Shirine",
    email: "doshirine18@opensource.org",
    telephone: "+86 400 151 0661",
    preferredLang: Language.Fr,
  },
  {
    id: 46,
    firstName: "Marja",
    lastName: "Ewestace",
    email: "mewestace19@wiley.com",
    telephone: "+351 247 688 2810",
    preferredLang: Language.Fr,
  },
  {
    id: 47,
    firstName: "Deeanne",
    lastName: "MacGinley",
    email: "dmacginley1a@themeforest.net",
    telephone: "+351 224 553 0539",
    preferredLang: Language.Fr,
  },
  {
    id: 48,
    firstName: "Denys",
    lastName: "Krollmann",
    email: "dkrollmann1b@cocolog-nifty.com",
    telephone: "+54 432 360 0689",
    preferredLang: Language.Fr,
  },
  {
    id: 49,
    firstName: "Cordie",
    lastName: "Girod",
    email: "cgirod1c@addtoany.com",
    telephone: "+86 783 402 8806",
    preferredLang: Language.Fr,
  },
  {
    id: 50,
    firstName: "Hilary",
    lastName: "Snowman",
    email: "hsnowman1d@cisco.com",
    telephone: "+86 432 909 4745",
    preferredLang: Language.Fr,
  },
  {
    id: 51,
    firstName: "Karena",
    lastName: "Whayman",
    email: "kwhayman1e@cdbaby.com",
    telephone: "+62 555 552 5551",
    preferredLang: Language.Fr,
  },
  {
    id: 52,
    firstName: "Ludovico",
    lastName: "Walklott",
    email: "lwalklott1f@barnesandnoble.com",
    telephone: "+33 226 464 9041",
    preferredLang: Language.Fr,
  },
  {
    id: 53,
    firstName: "Cordelie",
    lastName: "Kubasek",
    email: "ckubasek1g@aboutads.info",
    telephone: "+225 212 619 2895",
    preferredLang: Language.Fr,
  },
  {
    id: 54,
    firstName: "Leslie",
    lastName: "Gradon",
    email: "lgradon1h@addthis.com",
    telephone: "+57 418 505 3800",
    preferredLang: Language.Fr,
  },
  {
    id: 55,
    firstName: "Chaim",
    lastName: "Durrans",
    email: "cdurrans1i@smh.com.au",
    telephone: "+63 983 243 1995",
    preferredLang: Language.Fr,
  },
  {
    id: 56,
    firstName: "Alli",
    lastName: "Pladen",
    email: "apladen1j@dyndns.org",
    telephone: "+381 842 878 5209",
    preferredLang: Language.Fr,
  },
  {
    id: 57,
    firstName: "Berty",
    lastName: "Marnane",
    email: "bmarnane1k@google.it",
    telephone: "+98 615 847 2755",
    preferredLang: Language.Fr,
  },
  {
    id: 58,
    firstName: "Darbie",
    lastName: "Gallyon",
    email: "dgallyon1l@posterous.com",
    telephone: "+254 871 299 0634",
    preferredLang: Language.Fr,
  },
  {
    id: 59,
    firstName: "Teirtza",
    lastName: "Vogeler",
    email: "tvogeler1m@va.gov",
    telephone: "+30 964 874 4507",
    preferredLang: Language.En,
  },
  {
    id: 60,
    firstName: "Guillaume",
    lastName: "Adenet",
    email: "gadenet1n@prnewswire.com",
    telephone: "+855 146 482 4474",
    preferredLang: Language.Fr,
  },
  {
    id: 61,
    firstName: "Jacqui",
    lastName: "Bowerbank",
    email: "jbowerbank1o@cnet.com",
    telephone: "+386 165 808 0319",
    preferredLang: Language.Fr,
  },
  {
    id: 62,
    firstName: "Robinia",
    lastName: "Mutimer",
    email: "rmutimer1p@army.mil",
    telephone: "+216 406 809 9892",
    preferredLang: Language.Fr,
  },
  {
    id: 63,
    firstName: "Raychel",
    lastName: "Shailer",
    email: "rshailer1q@homestead.com",
    telephone: "+84 888 727 9467",
    preferredLang: Language.Fr,
  },
  {
    id: 64,
    firstName: "Blaine",
    lastName: "Wyre",
    email: "bwyre1r@examiner.com",
    telephone: "+46 747 621 9559",
    preferredLang: Language.Fr,
  },
  {
    id: 65,
    firstName: "Corbett",
    lastName: "Milton-White",
    email: "cmiltonwhite1s@vinaora.com",
    telephone: "+86 843 141 6708",
    preferredLang: Language.Fr,
  },
  {
    id: 66,
    firstName: "Halsy",
    lastName: "Howlett",
    email: "hhowlett1t@miitbeian.gov.cn",
    telephone: "+63 580 478 5657",
    preferredLang: Language.Fr,
  },
  {
    id: 67,
    firstName: "Ashby",
    lastName: "Gallichan",
    email: "agallichan1u@w3.org",
    telephone: "+86 917 924 9577",
    preferredLang: Language.Fr,
  },
  {
    id: 68,
    firstName: "Trumaine",
    lastName: "Cuddehay",
    email: "tcuddehay1v@army.mil",
    telephone: "+86 767 610 6124",
    preferredLang: Language.Fr,
  },
  {
    id: 69,
    firstName: "Tom",
    lastName: "McGonigle",
    email: "tmcgonigle1w@squidoo.com",
    telephone: "+86 913 914 2399",
    preferredLang: Language.Fr,
  },
  {
    id: 70,
    firstName: "Sue",
    lastName: "Smeuin",
    email: "ssmeuin1x@opera.com",
    telephone: "+387 860 343 1940",
    preferredLang: Language.Fr,
  },
  {
    id: 71,
    firstName: "Denny",
    lastName: "Adkins",
    email: "dadkins1y@china.com.cn",
    telephone: "+62 579 849 0172",
    preferredLang: Language.Fr,
  },
  {
    id: 72,
    firstName: "Merci",
    lastName: "Winsper",
    email: "mwinsper1z@123-reg.co.uk",
    telephone: "+62 225 237 9228",
    preferredLang: Language.Fr,
  },
  {
    id: 73,
    firstName: "Genevieve",
    lastName: "Shitliff",
    email: "gshitliff20@techcrunch.com",
    telephone: "+420 503 274 3255",
    preferredLang: Language.Fr,
  },
  {
    id: 74,
    firstName: "Misty",
    lastName: "Boyle",
    email: "mboyle21@bbc.co.uk",
    telephone: "+58 916 796 9228",
    preferredLang: Language.Fr,
  },
  {
    id: 75,
    firstName: "Laurice",
    lastName: "Vala",
    email: "lvala22@hugedomains.com",
    telephone: "+420 648 123 5123",
    preferredLang: Language.Fr,
  },
  {
    id: 76,
    firstName: "Ofelia",
    lastName: "Utterson",
    email: "outterson23@histats.com",
    telephone: "+86 161 183 2685",
    preferredLang: Language.Fr,
  },
  {
    id: 77,
    firstName: "Kira",
    lastName: "Arend",
    email: "karend24@berkeley.edu",
    telephone: "+60 370 334 2387",
    preferredLang: Language.Fr,
  },
  {
    id: 78,
    firstName: "Sheri",
    lastName: "Hendin",
    email: "shendin25@cafepress.com",
    telephone: "+48 369 443 7660",
    preferredLang: Language.Fr,
  },
  {
    id: 79,
    firstName: "Anselma",
    lastName: "Decourcy",
    email: "adecourcy26@sohu.com",
    telephone: "+7 544 606 4209",
    preferredLang: Language.Fr,
  },
  {
    id: 80,
    firstName: "Leonie",
    lastName: "Milkeham",
    email: "lmilkeham27@youku.com",
    telephone: "+86 849 210 3087",
    preferredLang: Language.Fr,
  },
  {
    id: 81,
    firstName: "Matti",
    lastName: "Sharpin",
    email: "msharpin28@who.int",
    telephone: "+86 617 812 9040",
    preferredLang: Language.Fr,
  },
  {
    id: 82,
    firstName: "Barbette",
    lastName: "Lumpkin",
    email: "blumpkin29@mtv.com",
    telephone: "+1 949 121 3704",
    preferredLang: Language.Fr,
  },
  {
    id: 83,
    firstName: "Pavia",
    lastName: "Flott",
    email: "pflott2a@webeden.co.uk",
    telephone: "+86 825 222 4861",
    preferredLang: Language.Fr,
  },
  {
    id: 84,
    firstName: "Brande",
    lastName: "Guidelli",
    email: "bguidelli2b@kickstarter.com",
    telephone: "+502 278 880 8851",
    preferredLang: Language.Fr,
  },
  {
    id: 85,
    firstName: "Bernarr",
    lastName: "Goncaves",
    email: "bgoncaves2c@hubpages.com",
    telephone: "+51 854 149 7534",
    preferredLang: Language.Fr,
  },
  {
    id: 86,
    firstName: "Iosep",
    lastName: "Mosdell",
    email: "imosdell2d@slideshare.net",
    telephone: "+63 733 341 1213",
    preferredLang: Language.Fr,
  },
  {
    id: 87,
    firstName: "Kasey",
    lastName: "Phillipps",
    email: "kphillipps2e@vkontakte.ru",
    telephone: "+244 105 710 7474",
    preferredLang: Language.Fr,
  },
  {
    id: 88,
    firstName: "Maribel",
    lastName: "Trahmel",
    email: "mtrahmel2f@mapy.cz",
    telephone: "+62 257 793 1488",
    preferredLang: Language.Fr,
  },
  {
    id: 89,
    firstName: "Bartlet",
    lastName: "Tart",
    email: "btart2g@apple.com",
    telephone: "+86 645 578 7548",
    preferredLang: Language.Fr,
  },
  {
    id: 90,
    firstName: "Tanitansy",
    lastName: "Garman",
    email: "tgarman2h@free.fr",
    telephone: "+55 969 777 9522",
    preferredLang: Language.Fr,
  },
  {
    id: 91,
    firstName: "Christophorus",
    lastName: "Evennett",
    email: "cevennett2i@smh.com.au",
    telephone: "+7 752 850 2992",
    preferredLang: Language.Fr,
  },
  {
    id: 92,
    firstName: "Darb",
    lastName: "Toone",
    email: "dtoone2j@aboutads.info",
    telephone: "+351 452 932 5675",
    preferredLang: Language.Fr,
  },
  {
    id: 93,
    firstName: "Audy",
    lastName: "Lambarton",
    email: "alambarton2k@ihg.com",
    telephone: "+57 541 604 6990",
    preferredLang: Language.Fr,
  },
  {
    id: 94,
    firstName: "Sonny",
    lastName: "Lintall",
    email: "slintall2l@harvard.edu",
    telephone: "+86 833 917 8226",
    preferredLang: Language.Fr,
  },
  {
    id: 95,
    firstName: "Parke",
    lastName: "Sawell",
    email: "psawell2m@cnbc.com",
    telephone: "+86 725 455 5597",
    preferredLang: Language.Fr,
  },
  {
    id: 96,
    firstName: "Bab",
    lastName: "Meneur",
    email: "bmeneur2n@economist.com",
    telephone: "+86 366 860 5678",
    preferredLang: Language.Fr,
  },
  {
    id: 97,
    firstName: "Pearce",
    lastName: "Ivain",
    email: "pivain2o@state.gov",
    telephone: "+49 855 150 9397",
    preferredLang: Language.Fr,
  },
  {
    id: 98,
    firstName: "Glenna",
    lastName: "Pearcy",
    email: "gpearcy2p@scientificamerican.com",
    telephone: "+27 761 731 0907",
    preferredLang: Language.Fr,
  },
  {
    id: 99,
    firstName: "Eudora",
    lastName: "Concannon",
    email: "econcannon2q@shinystat.com",
    telephone: "+86 284 308 9841",
    preferredLang: Language.En,
  },
  {
    id: 100,
    firstName: "Raffaello",
    lastName: "Croshaw",
    email: "rcroshaw2r@wisc.edu",
    telephone: "+420 751 660 0638",
    preferredLang: Language.Fr,
  },
];
