/// <reference types="vite/client" />
declare const IS_DEV_SERVER: boolean;
declare const API_HOST: string;
declare const API_URI: string;
declare const API_PROTECTED_URI: string;
declare const BUILD_DATE: string;
declare const VERSION: string;
declare const COMMIT_HASH: string;
declare const TALENTSEARCH_SUPPORT_EMAIL: string;
declare const API_SUPPORT_ENDPOINT: string;
