blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/GCTC-NTGC/gc-digital-talent/discussions
    about: Ask questions and discuss with other community members
