name: Feature Request
description: A new feature or change to existing functionality.
title: "✨ "
projects: ["GCTC-NTGC/8"]
type: "Feature"
body:
  - type: markdown
    attributes:
      value: "## ✨ Feature Request"
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature issue!
  - type: textarea
    id: description-feature
    attributes:
      label: Details
      description: Describe the feature that is being requested.
  - type: markdown
    attributes:
      value: "## 🎨 Design"
  - type: textarea
    id: design
    attributes:
      label: Design file & designer
      description: Include a link to the design file (if it exists) and the author.
  - type: textarea
    id: screenshot
    attributes:
      label: 📸 Screenshots
      description: Paste a screenshot to help illustrate the feature.
  - type: textarea
    id: localization
    attributes:
      label: 🌎 Localization
      description: Provide any new copy along with translations available.
  - type: markdown
    attributes:
      value: "## 🙋‍♀️ Implementation"
  - type: textarea
    id: proposed-implementation
    attributes:
      label: Proposed Implementation
      description: Do you have a proposed implementation?
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: A set of assumptions which, when tested, verify that the bug was addressed.
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
  - type: markdown
    attributes:
      value: |
        ### 🚢 Definition of Ready
        Ensure the issue meets the criteria in our [Definition of Ready](../blob/main/documentation/definition-of-ready.md) before it can be accepted for development.
