name: "Spike"
description: Conduct research or prototype an aspect of a solution to prove its viability.
title: "🦔 "
projects: ["GCTC-NTGC/8"]
type: "Spike"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this spike issue!
  - type: textarea
    id: description
    attributes:
      label: 🦔 Spike
      description: Describe the spike.
  - type: textarea
    id: questions-to-answer
    attributes:
      label: ❓ Questions to answer
      description: What specific questions need to have been answered for this task to be considered complete?
  - type: textarea
    id: timebox
    attributes:
      label: 🕙 Timebox
      description: How many days are we expected to spend on this?
