name: "Testing"
description: Verifying whether the app is working as expected or not.
title: "🧪 "
projects: ["GCTC-NTGC/8"]
type: "Testing"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this testing issue!
  - type: input
    id: target-bug-feature
    attributes:
      label: 🎯 Target Bug(s) / Feature
      description: Reference the related bug, regression, or feature here.
      placeholder: e.g., #14342, Department creation, login flow, etc.
  - type: input
    id: test-type
    attributes:
      label: 🛠 Test Type
      description: Specify "unit test" or "e2e test"
      placeholder: e2e test
  - type: input
    id: scope
    attributes:
      label: 📍 Scope / Component
      description: Which app component or feature is being tested?
      placeholder: e.g., Departments, Users, Job Process, etc.
  - type: textarea
    id: objective
    attributes:
      label: ✅ Test Objective
      description: Describe the objective of the test, such as which bug fix, regression, or new feature to verify and the expected behavior.
      placeholder: |
        e.g., Verify that creating a new department works as expected and does not throw errors.
  - type: textarea
    id: steps
    attributes:
      label: 📝 Test Steps
      description: List the steps required to execute the test.
      placeholder: |
        1. Log in as admin
        2. Navigate to Departments and click create
        3. Fill all mandatory fields and submit
        4. Verify outcome
  - type: textarea
    id: assertions
    attributes:
      label: 📋 Assertions
      description: List the specific outcomes or states that must be verified for each step.
      placeholder: |
        - New department appears in the list
        - No errors shown in UI or console
        - Creation is reflected in backend/API
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: A set of criteria which, when tested, verify that the tests are correctly updated and working.
      placeholder: |
        - [ ] Department is listed after creation
        - [ ] No error messages appear
        - [ ] API shows new department
