name: "Tooling"
description: Updates to the CI pipeline
title: "🛠️ "
projects: ["GCTC-NTGC/8"]
type: "Debt"
labels: tooling
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this tooling issue!
  - type: textarea
    id: description
    attributes:
      label: 🛠️ Tooling
      description: Describe the additions/changes you would like to see to the tooling.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: 🕵️ Details
      description: Add any additional details that could assist with the changes/additions being made.
  - type: textarea
    id: proposed-solution
    attributes:
      label: 🙋‍♀️ Proposed Solution
      description: How do you think we can improve this?
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: A set of assumptions which, when tested, verify that the tooling was properly updated and remains functional.
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
