import {
  salaryRanges,
  getSalaryRange,
  languages,
  getLanguage,
  educationRequirements,
  getEducationRequirement,
  languageAbilities,
  getLanguageAbility,
  employmentEquityStatements,
  getEmploymentEquityStatement,
  employmentEquityGroups,
  getEmploymentEquityGroup,
  indigenousCommunities,
  getIndigenousCommunity,
} from "./localizedConstants";

export {
  salaryRanges,
  getSalaryRange,
  languages,
  getLanguage,
  educationRequirements,
  getEducationRequirement,
  languageAbilities,
  getLanguageAbility,
  employmentEquityStatements,
  getEmploymentEquityStatement,
  employmentEquityGroups,
  getEmploymentEquityGroup,
  indigenousCommunities,
  getIndigenousCommunity,
};
