<?php

namespace Database\Seeders;

use App\Enums\DepartmentSize;
use App\Models\Department;
use Illuminate\Database\Seeder;

class DepartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        /*
        A SQL query to help recreate this array:

        select
            format(
                '[
                ''department_number'' => %s,
                ''name'' => [
                ''en'' => ''%s'',
                ''fr'' => ''%s'',
                ],
                ''org_identifier'' => %s,
            ''is_core_public_administration'' => %s,
            ''is_central_agency'' => %s,
            ''is_science'' => %s,
            ''is_regulatory'' => %s,
            ''size'' => %s,
            ],',
            d.department_number,
            replace(d."Dept Names - EN", '''', '\'''),
            replace(d."Dept Name FR", '''', '\'''),
            case d."OrgID" when 'N/A' then 'null' else d."OrgID" end,
                case d."CPA (Yes/No)" when 'Yes' then 'true' else 'false' end,
                case d."Central Agency (Yes/No)" when 'Yes' then 'true' else 'false' end,
                case d."Science department or agency (Yes/No)" when 'Yes' then 'true' else 'false' end,
                case d."Regulatory departments or agency (Yes/No)" when 'Yes' then 'true' else 'false' end,
            'DepartmentSize::' || upper(d."Department size (micro, Small, Medium, Large)") || '->name'
            )
        from department_list_spreadsheet d
        order by department_number
        */

        $departments = [
            [
                'department_number' => 1,
                'name' => [
                    'en' => 'Agriculture and Agri-Food Canada',
                    'fr' => 'Agriculture et Agroalimentaire Canada',
                ],
                'org_identifier' => 1,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => true,
                'is_regulatory' => true,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 2,
                'name' => [
                    'en' => 'Office of the Auditor General of Canada',
                    'fr' => 'Bureau du vérificateur général du Canada',
                ],
                'org_identifier' => 238,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 4,
                'name' => [
                    'en' => 'Public Service Commission of Canada',
                    'fr' => 'Commission de la fonction publique du Canada',
                ],
                'org_identifier' => 282,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 5,
                'name' => [
                    'en' => 'Global Affairs Canada',
                    'fr' => 'Affaires mondiales Canada',
                ],
                'org_identifier' => 126,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => true,
                'is_regulatory' => false,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 6,
                'name' => [
                    'en' => 'Department of Finance Canada',
                    'fr' => 'Ministère des Finances Canada',
                ],
                'org_identifier' => 124,
                'is_core_public_administration' => true,
                'is_central_agency' => true,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 7,
                'name' => [
                    'en' => 'Environment and Climate Change Canada',
                    'fr' => 'Environnement et Changement climatique Canada',
                ],
                'org_identifier' => 137,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => true,
                'is_regulatory' => true,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 8,
                'name' => [
                    'en' => 'Office of the Secretary to the Governor General',
                    'fr' => 'Bureau du secrétaire du gouverneur général',
                ],
                'org_identifier' => 249,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 9,
                'name' => [
                    'en' => 'Senate',
                    'fr' => 'Sénat',
                ],
                'org_identifier' => 303,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 11,
                'name' => [
                    'en' => 'Office of the Superintendent of Financial Institutions Canada',
                    'fr' => 'Bureau du surintendant des institutions financières Canada',
                ],
                'org_identifier' => 253,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 12,
                'name' => [
                    'en' => 'Canada Economic Development for Quebec Regions',
                    'fr' => 'Développement économique Canada pour les régions du Québec',
                ],
                'org_identifier' => 141,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 13,
                'name' => [
                    'en' => 'Department of Justice Canada',
                    'fr' => 'Ministère de la Justice Canada',
                ],
                'org_identifier' => 132,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 14,
                'name' => [
                    'en' => 'Employment and Social Development Canada',
                    'fr' => 'Emploi et Développement social Canada',
                ],
                'org_identifier' => 128,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 15,
                'name' => [
                    'en' => 'Elections Canada',
                    'fr' => 'Bureau du directeur général des élections',
                ],
                'org_identifier' => 239,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 16,
                'name' => [
                    'en' => 'Canadian Radio-television and Telecommunications Commission',
                    'fr' => 'Conseil de la radiodiffusion et des télécommunications canadiennes',
                ],
                'org_identifier' => 93,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 17,
                'name' => [
                    'en' => 'Library of Parliament',
                    'fr' => 'Bibliothèque du Parlement',
                ],
                'org_identifier' => 200,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 18,
                'name' => [
                    'en' => 'National Defence',
                    'fr' => 'Défense nationale',
                ],
                'org_identifier' => 133,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => true,
                'is_regulatory' => false,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 19,
                'name' => [
                    'en' => 'Public Prosecution Service of Canada',
                    'fr' => 'Service des poursuites pénales du Canada',
                ],
                'org_identifier' => 248,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 21,
                'name' => [
                    'en' => 'Veterans Affairs Canada',
                    'fr' => 'Anciens Combattants Canada',
                ],
                'org_identifier' => 139,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 22,
                'name' => [
                    'en' => 'Health Canada',
                    'fr' => 'Santé Canada',
                ],
                'org_identifier' => 127,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => true,
                'is_regulatory' => true,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 23,
                'name' => [
                    'en' => 'Atlantic Canada Opportunities Agency',
                    'fr' => 'Agence de promotion économique du Canada atlantique',
                ],
                'org_identifier' => 12,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 24,
                'name' => [
                    'en' => 'International Joint Commission (Canadian Section)',
                    'fr' => 'Commission mixte internationale (section canadienne)',
                ],
                'org_identifier' => 189,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 25,
                'name' => [
                    'en' => 'Privy Council Office',
                    'fr' => 'Bureau du Conseil privé',
                ],
                'org_identifier' => 278,
                'is_core_public_administration' => true,
                'is_central_agency' => true,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 27,
                'name' => [
                    'en' => 'Natural Sciences and Engineering Research Council of Canada',
                    'fr' => 'Conseil de recherches en sciences naturelles et en génie du Canada',
                ],
                'org_identifier' => 230,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => true,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 30,
                'name' => [
                    'en' => 'Royal Canadian Mounted Police',
                    'fr' => 'Gendarmerie royale du Canada',
                ],
                'org_identifier' => 295,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 32,
                'name' => [
                    'en' => 'Immigration and Refugee Board of Canada',
                    'fr' => 'Commission de l\'immigration et du statut de réfugié du Canada',
                ],
                'org_identifier' => 174,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 33,
                'name' => [
                    'en' => 'Innovation, Science and Economic Development Canada',
                    'fr' => 'Innovation, Sciences et Développement économique Canada',
                ],
                'org_identifier' => 130,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => true,
                'is_regulatory' => true,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 34,
                'name' => [
                    'en' => 'Transport Canada',
                    'fr' => 'Transports Canada',
                ],
                'org_identifier' => 138,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 35,
                'name' => [
                    'en' => 'National Research Council Canada',
                    'fr' => 'Conseil national de recherches Canada',
                ],
                'org_identifier' => 228,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => true,
                'is_regulatory' => false,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 39,
                'name' => [
                    'en' => 'National Film Board',
                    'fr' => 'Office national du film',
                ],
                'org_identifier' => 223,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 40,
                'name' => [
                    'en' => 'Canadian Transportation Agency',
                    'fr' => 'Office des transports du Canada',
                ],
                'org_identifier' => 99,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 41,
                'name' => [
                    'en' => 'Natural Resources Canada',
                    'fr' => 'Ressources naturelles Canada',
                ],
                'org_identifier' => 134,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => true,
                'is_regulatory' => true,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 42,
                'name' => [
                    'en' => 'Crown-Indigenous Relations and Northern Affairs Canada',
                    'fr' => 'Relations Couronne-Autochtones et Affaires du Nord Canada',
                ],
                'org_identifier' => 129,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 43,
                'name' => [
                    'en' => 'Canadian Intergovernmental Conference Secretariat',
                    'fr' => 'Secrétariat des conférences intergouvernementales canadiennes',
                ],
                'org_identifier' => 76,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 46,
                'name' => [
                    'en' => 'Office of the Public Sector Integrity Commissioner of Canada',
                    'fr' => 'Commissariat à l\'intégrité du secteur public du Canada',
                ],
                'org_identifier' => 250,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 47,
                'name' => [
                    'en' => 'Canadian Nuclear Safety Commission',
                    'fr' => 'Commission canadienne de sûreté nucléaire',
                ],
                'org_identifier' => 87,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 50,
                'name' => [
                    'en' => 'Immigration, Refugees and Citizenship Canada',
                    'fr' => 'Immigration, Réfugiés et Citoyenneté Canada',
                ],
                'org_identifier' => 123,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 51,
                'name' => [
                    'en' => 'Office of the Commissioner for Federal Judicial Affairs Canada',
                    'fr' => 'Commissariat à la magistrature fédérale Canada',
                ],
                'org_identifier' => 240,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 52,
                'name' => [
                    'en' => 'Canada School of Public Service',
                    'fr' => 'École de la fonction publique du Canada',
                ],
                'org_identifier' => 47,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 53,
                'name' => [
                    'en' => 'Correctional Service Canada',
                    'fr' => 'Service correctionnel Canada',
                ],
                'org_identifier' => 117,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 54,
                'name' => [
                    'en' => 'Statistics Canada',
                    'fr' => 'Statistique Canada',
                ],
                'org_identifier' => 313,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => true,
                'is_regulatory' => false,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 56,
                'name' => [
                    'en' => 'Treasury Board of Canada Secretariat',
                    'fr' => 'Secrétariat du Conseil du Trésor du Canada',
                ],
                'org_identifier' => 326,
                'is_core_public_administration' => true,
                'is_central_agency' => true,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 57,
                'name' => [
                    'en' => 'Parole Board of Canada',
                    'fr' => 'Commission des libérations conditionnelles du Canada',
                ],
                'org_identifier' => 227,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 61,
                'name' => [
                    'en' => 'Canadian Institutes of Health Research',
                    'fr' => 'Instituts de recherche en santé du Canada',
                ],
                'org_identifier' => 74,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => true,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 62,
                'name' => [
                    'en' => 'Federal Economic Development Agency for Southern Ontario',
                    'fr' => 'Agence fédérale de développement économique pour le Sud de l\'Ontario',
                ],
                'org_identifier' => 150,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 63,
                'name' => [
                    'en' => 'Social Sciences and Humanities Research Council of Canada',
                    'fr' => 'Conseil de recherches en sciences humaines du Canada',
                ],
                'org_identifier' => 306,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => true,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 66,
                'name' => [
                    'en' => 'Northern Pipeline Agency Canada',
                    'fr' => 'Administration du pipe-line du Nord Canada',
                ],
                'org_identifier' => 235,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 67,
                'name' => [
                    'en' => 'House of Commons',
                    'fr' => 'Chambre des communes',
                ],
                'org_identifier' => 2,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 75,
                'name' => [
                    'en' => 'Canadian Human Rights Commission',
                    'fr' => 'Commission canadienne des droits de la personne',
                ],
                'org_identifier' => 71,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 76,
                'name' => [
                    'en' => 'Office of the Commissioner of Official Languages',
                    'fr' => 'Commissariat aux langues officielles',
                ],
                'org_identifier' => 242,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 78,
                'name' => [
                    'en' => 'Canadian Northern Economic Development Agency',
                    'fr' => 'Agence canadienne de développement économique du Nord',
                ],
                'org_identifier' => 86,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 80,
                'name' => [
                    'en' => 'Registrar of the Supreme Court of Canada',
                    'fr' => 'Registraire de la Cour suprême du Canada',
                ],
                'org_identifier' => 288,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 85,
                'name' => [
                    'en' => 'Canada Border Services Agency',
                    'fr' => 'Agence des services frontaliers du Canada',
                ],
                'org_identifier' => 26,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 86,
                'name' => [
                    'en' => 'Fisheries and Oceans Canada',
                    'fr' => 'Pêches et Océans Canada',
                ],
                'org_identifier' => 125,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => true,
                'is_regulatory' => true,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 88,
                'name' => [
                    'en' => 'Public Safety Canada',
                    'fr' => 'Sécurité publique Canada',
                ],
                'org_identifier' => 135,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 95,
                'name' => [
                    'en' => 'Canadian Security Intelligence Service',
                    'fr' => 'Service canadien du renseignement de sécurité',
                ],
                'org_identifier' => 94,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 96,
                'name' => [
                    'en' => 'Offices of the Information and Privacy Commissioners of Canada',
                    'fr' => 'Commissariats à l’information et à la protection de la vie privée du Canada',
                ],
                'org_identifier' => 256,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 97,
                'name' => [
                    'en' => 'Receiver General',
                    'fr' => 'Receveur général',
                ],
                'org_identifier' => null,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 100,
                'name' => [
                    'en' => 'Canadian Centre for Occupational Health and Safety',
                    'fr' => 'Centre canadien d’hygiène et de sécurité au travail',
                ],
                'org_identifier' => 55,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 101,
                'name' => [
                    'en' => 'Transportation Safety Board of Canada',
                    'fr' => 'Bureau de la sécurité des transports du Canada',
                ],
                'org_identifier' => 98,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 102,
                'name' => [
                    'en' => 'The National Battlefields Commission',
                    'fr' => 'Commission des champs de bataille nationaux',
                ],
                'org_identifier' => 218,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 109,
                'name' => [
                    'en' => 'Patented Medicine Prices Review Board Canada',
                    'fr' => 'Conseil d\'examen du prix des médicaments brevetés Canada',
                ],
                'org_identifier' => 266,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 116,
                'name' => [
                    'en' => 'Copyright Board Canada',
                    'fr' => 'Commission du droit d\'auteur Canada',
                ],
                'org_identifier' => 114,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 119,
                'name' => [
                    'en' => 'Canadian Space Agency',
                    'fr' => 'Agence spatiale canadienne',
                ],
                'org_identifier' => 95,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => true,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 124,
                'name' => [
                    'en' => 'Parks Canada',
                    'fr' => 'Parcs Canada',
                ],
                'org_identifier' => 263,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 127,
                'name' => [
                    'en' => 'Public Services and Procurement Canada',
                    'fr' => 'Services publics et Approvisionnement Canada',
                ],
                'org_identifier' => 136,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 130,
                'name' => [
                    'en' => 'Canada Revenue Agency',
                    'fr' => 'Agence du revenu du Canada',
                ],
                'org_identifier' => 46,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 133,
                'name' => [
                    'en' => 'Canadian Grain Commission',
                    'fr' => 'Commission canadienne des grains',
                ],
                'org_identifier' => 69,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 134,
                'name' => [
                    'en' => 'Canadian Dairy Commission',
                    'fr' => 'Commission canadienne du lait',
                ],
                'org_identifier' => 61,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 135,
                'name' => [
                    'en' => 'Canadian Heritage',
                    'fr' => 'Patrimoine canadien',
                ],
                'org_identifier' => 122,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 136,
                'name' => [
                    'en' => 'Canadian Food Inspection Agency',
                    'fr' => 'Agence canadienne d\'inspection des aliments',
                ],
                'org_identifier' => 65,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 137,
                'name' => [
                    'en' => 'Military Police Complaints Commission of Canada',
                    'fr' => 'Commission d\'examen des plaintes concernant la police militaire du Canada',
                ],
                'org_identifier' => 210,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 138,
                'name' => [
                    'en' => 'Military Grievances External Review Committee',
                    'fr' => 'Comité externe d\'examen des griefs militaires',
                ],
                'org_identifier' => 209,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 139,
                'name' => [
                    'en' => 'Financial Transactions and Reports Analysis Centre of Canada',
                    'fr' => 'Centre d\'analyse des opérations et déclarations financières du Canada',
                ],
                'org_identifier' => 152,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 141,
                'name' => [
                    'en' => 'Financial Consumer Agency of Canada',
                    'fr' => 'Agence de la consommation en matière financière du Canada',
                ],
                'org_identifier' => 151,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 144,
                'name' => [
                    'en' => 'Courts Administration Service',
                    'fr' => 'Service administratif des tribunaux judiciaires',
                ],
                'org_identifier' => 118,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 145,
                'name' => [
                    'en' => 'Library and Archives Canada',
                    'fr' => 'Bibliothèque et Archives Canada',
                ],
                'org_identifier' => 199,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 147,
                'name' => [
                    'en' => 'Office of the Conflict of Interest and Ethics Commissioner',
                    'fr' => 'Commissariat aux conflits d\'intérêts et à l\'éthique',
                ],
                'org_identifier' => 245,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 148,
                'name' => [
                    'en' => 'Public Health Agency of Canada',
                    'fr' => 'Agence de la santé publique du Canada',
                ],
                'org_identifier' => 280,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => true,
                'is_regulatory' => true,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 154,
                'name' => [
                    'en' => 'Office of the Commissioner of Lobbying of Canada',
                    'fr' => 'Commissariat au lobbying du Canada',
                ],
                'org_identifier' => 241,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 163,
                'name' => [
                    'en' => 'Shared Services Canada',
                    'fr' => 'Services partagés Canada',
                ],
                'org_identifier' => 305,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 165,
                'name' => [
                    'en' => 'Communications Security Establishment Canada',
                    'fr' => 'Centre de la sécurité des télécommunications Canada',
                ],
                'org_identifier' => 110,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 170,
                'name' => [
                    'en' => 'Administrative Tribunals Support Service of Canada',
                    'fr' => 'Service canadien d\'appui aux tribunaux administratifs',
                ],
                'org_identifier' => 539,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 171,
                'name' => [
                    'en' => 'Polar Knowledge Canada',
                    'fr' => 'Savoir polaire Canada',
                ],
                'org_identifier' => 552,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 176,
                'name' => [
                    'en' => 'Parliamentary Protective Service',
                    'fr' => 'Service de protection parlementaire',
                ],
                'org_identifier' => 554,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 180,
                'name' => [
                    'en' => 'Invest in Canada Hub',
                    'fr' => 'Investir au Canada',
                ],
                'org_identifier' => 347,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 183,
                'name' => [
                    'en' => 'Office of the Parliamentary Budget Officer',
                    'fr' => 'Bureau du directeur parlementaire du budget',
                ],
                'org_identifier' => 346,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 190,
                'name' => [
                    'en' => 'Women and Gender Equality Canada',
                    'fr' => 'Femmes et Égalité des genres Canada',
                ],
                'org_identifier' => 246,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 191,
                'name' => [
                    'en' => 'Indigenous Services Canada',
                    'fr' => 'Ministère des Services aux Autochtones',
                ],
                'org_identifier' => 348,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::LARGE->name,
            ],
            [
                'department_number' => 192,
                'name' => [
                    'en' => 'Secretariat of the National Security and Intelligence Committee of Parliamentarians',
                    'fr' => 'Secrétariat du Comité des parlementaires sur la sécurité nationale et le renseignement',
                ],
                'org_identifier' => 345,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 193,
                'name' => [
                    'en' => 'Leaders’ Debates Commission',
                    'fr' => 'Commission des débats des chefs',
                ],
                'org_identifier' => 350,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 195,
                'name' => [
                    'en' => 'Canada Energy Regulator',
                    'fr' => 'Régie de l\'énergie du Canada',
                ],
                'org_identifier' => 221,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 196,
                'name' => [
                    'en' => 'National Security and Intelligence Review Agency Secretariat',
                    'fr' => 'Secrétariat de l’Office de surveillance des activités en matière de sécurité nationale et de renseignement',
                ],
                'org_identifier' => 302,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 197,
                'name' => [
                    'en' => 'Office of the Intelligence Commissioner',
                    'fr' => 'Bureau du commissaire au renseignement',
                ],
                'org_identifier' => 244,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 201,
                'name' => [
                    'en' => 'Housing, Infrastructure and Communities Canada',
                    'fr' => 'Logement, Infrastructure et Collectivités Canada',
                ],
                'org_identifier' => 237,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MEDIUM->name,
            ],
            [
                'department_number' => 202,
                'name' => [
                    'en' => 'Impact Assessment Agency of Canada',
                    'fr' => 'Agence d\'évaluation d\'impact du Canada',
                ],
                'org_identifier' => 63,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => true,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 204,
                'name' => [
                    'en' => 'Canada Water Agency',
                    'fr' => 'Agence canadienne de l’eau',
                ],
                'org_identifier' => 563,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 205,
                'name' => [
                    'en' => 'Farm Products Council of Canada',
                    'fr' => 'Conseil des produits agricoles du Canada',
                ],
                'org_identifier' => 222,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 206,
                'name' => [
                    'en' => 'Federal Economic Development Agency for Northern Ontario',
                    'fr' => 'Agence fédérale de développement économique pour le Nord de l’Ontario',
                ],
                'org_identifier' => 561,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 208,
                'name' => [
                    'en' => 'Law Commission of Canada',
                    'fr' => 'Commission du droit du Canada',
                ],
                'org_identifier' => 198,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 209,
                'name' => [
                    'en' => 'Office of the Chief Military Judge',
                    'fr' => 'Le cabinet du juge militaire en chef',
                ],
                'org_identifier' => null,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 210,
                'name' => [
                    'en' => 'Prairies Economic Development Canada',
                    'fr' => 'Développement économique Canada pour les Prairies',
                ],
                'org_identifier' => 140,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 213,
                'name' => [
                    'en' => 'RCMP External Review Committee',
                    'fr' => 'Comité externe d\'examen de la GRC',
                ],
                'org_identifier' => 296,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 216,
                'name' => [
                    'en' => 'Office of the Information Commissioner of Canada',
                    'fr' => 'Commissariat à l\'information au Canada',
                ],
                'org_identifier' => 256,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::SMALL->name,
            ],
            [
                'department_number' => 217,
                'name' => [
                    'en' => 'Veterans Review and Appeal Board',
                    'fr' => 'Tribunal des anciens combattants (révision et appel)',
                ],
                'org_identifier' => 333,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 218,
                'name' => [
                    'en' => 'Civilian Review and Complaints Commission for the RCMP',
                    'fr' => 'Commission civile d’examen et de traitement des plaintes relatives à la GRC',
                ],
                'org_identifier' => 297,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 900,
                'name' => [
                    'en' => 'The Correctional Investigator Canada',
                    'fr' => 'L\'Enquêteur correctionnel Canada',
                ],
                'org_identifier' => 247,
                'is_core_public_administration' => false,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
            [
                'department_number' => 903,
                'name' => [
                    'en' => 'Accessibility Standards Canada',
                    'fr' => 'Normes d\'accessibilité Canada',
                ],
                'org_identifier' => 558,
                'is_core_public_administration' => true,
                'is_central_agency' => false,
                'is_science' => false,
                'is_regulatory' => false,
                'size' => DepartmentSize::MICRO->name,
            ],
        ];

        foreach ($departments as $department) {
            $identifier = [
                'department_number' => $department['department_number'],
            ];
            Department::updateOrCreate($identifier, $department);
        }
    }
}
