<?php

namespace App\Enums;

enum AssessmentResultJustification
{
    case EDUCATION_ACCEPTED_INFORMATION;
    case EDUCATION_ACCEPTED_WORK_EXPERIENCE_EQUIVALENCY;
    case EDUCATION_ACCEPTED_COMBINATION_EDUCATION_WORK_EXPERIENCE;
    case EDUCATION_FAILED_NOT_RELEVANT;
    case EDUCATION_FAILED_REQUIREMENT_NOT_MET;
    case SKILL_ACCEPTED;
    case SKILL_FAILED_INSUFFICIENTLY_DEMONSTRATED;
    case FAILED_NOT_ENOUGH_INFORMATION;
    case FAILED_OTHER;
}
