<?php

namespace App\Enums;

enum ErrorCode
{
    // General
    case ALREADY_SUBMITTED;
    case KEY_IN_USE;

    // Application
    case APPLICATION_NOT_SUBMITTED;
    case APPLICATION_EDUCATION_REQUIREMENT_INCOMPLETE;
    case APPLICATION_EXISTS;
    case APPLICATION_MISSING_ESSENTIAL_SKILLS;
    case APPLICATION_MISSING_LANGUAGE_REQUIREMENTS;
    case APPLICATION_MISSING_QUESTION_RESPONSE;
    case APPLICATION_NOT_DRAFT;
    case APPLICATION_PROFILE_INCOMPLETE;
    case APPLICATION_POOL_CLOSED;
    case APPLICATION_POOL_NOT_PUBLISHED;
    case APPLICATION_SIGNATURE_REQUIRED;

    // Department
    case DEPARTMENT_NUMBER_IN_USE;

    // Notifications
    case CANNOT_ENABLE_NOTIFICATION_FAMILY;

    // Pool
    case CLOSING_DATE_REQUIRED;
    case CLOSING_DATE_FUTURE;
    case LOCATION_REQUIRED;
    case ESSENTIAL_SKILL_REQUIRED;
    case ESSENTIAL_SKILLS_CONTAINS_DELETED;
    case NONESSENTIAL_SKILLS_CONTAINS_DELETED;
    case ENGLISH_KEY_TASKS_REQUIRED;
    case FRENCH_KEY_TASKS_REQUIRED;
    case ENGLISH_YOUR_IMPACT_REQUIRED;
    case FRENCH_YOUR_IMPACT_REQUIRED;
    case ENGLISH_SPECIAL_NOTE_REQUIRED;
    case FRENCH_SPECIAL_NOTE_REQUIRED;
    case POOL_AREA_OF_SELECTION_REQUIRED;
    case CONTACT_EMAIL_REQUIRED;

    // Talent nominations
    case NO_NOMINATIONS_FOR_ADVANCEMENT_TO_DECIDE;
    case NO_NOMINATIONS_FOR_LATERAL_MOVEMENT_TO_DECIDE;
    case NO_NOMINATIONS_FOR_DEVELOPMENT_PROGRAMS_TO_DECIDE;
    case SKILL_NOT_KLC;
    case SKILLS_NOT_ALLOWED_FOR_EVENT;

    // User
    case UPDATE_USER_BOTH_STATUS_NON_STATUS;
    case SKILL_USED_ACTIVE_POSTER;
    case FAILED_DUE_SKILL_DELETED;
    case CANNOT_REOPEN_DELETED_SKILL;
    case MISSING_SUBSTANTIVE_EXPERIENCE;
    case TOO_MANY_SUBSTANTIVE_EXPERIENCES;
    case NOT_GOVERNMENT_EMAIL;
    case NOT_VERIFIED_GOVERNMENT_EMPLOYEE;

}
