<?php

namespace App\Enums;

enum ErrorCode
{
    // General
    case KEY_IN_USE;
    case EXPIRY_DATE_REQUIRED;
    case EXPIRY_DATE_AFTER_TODAY;
    case ARRAY_CONTAINS_DUPLICATES;

    // Application
    case APPLICATION_ALREADY_SUBMITTED;
    case APPLICATION_NOT_SUBMITTED;
    case APPLICATION_EDUCATION_REQUIREMENT_INCOMPLETE;
    case APPLICATION_EXISTS;
    case APPLICATION_MISSING_ESSENTIAL_SKILLS;
    case APPLICATION_MISSING_LANGUAGE_REQUIREMENTS;
    case APPLICATION_MISSING_QUESTION_RESPONSE;
    case APPLICATION_NOT_DRAFT;
    case APPLICATION_PROFILE_INCOMPLETE;
    case APPLICATION_POOL_CLOSED;
    case APPLICATION_POOL_NOT_PUBLISHED;
    case APPLICATION_SIGNATURE_REQUIRED;
    case APPLICATION_DELETE_FAILED;
    case APPLICATION_WORK_EMAIL_NOT_VERIFIED;

    // Assessment Plan
    case ASSESSMENT_STEP_MISSING_SKILLS;
    case POOL_SKILLS_WITHOUT_ASSESSMENTS;
    case ASSESSMENT_STEP_CANNOT_SWAP;

    // Assessment Result
    case ASSESSMENT_RESULT_REFERENCES_MULTIPLE_POOLS;
    case SKILL_JUSTIFICATION_FOR_EDUCATION_ASSESSMENT;
    case EDUCATION_JUSTIFICATIONS_FOR_SKILL_ASSESSMENT;
    case SKILL_ASSESSMENT_RESULT_MISSING_SKILL;
    case CANNOT_SET_ASSESSMENT_DECISION_LEVEL_FOR_THIS_TYPE_OR_DECISION;
    case ASSESSMENT_RESULT_ALREADY_EXISTS;
    case ASSESSMENT_STEPS_SAME_POOL;

    // Classification
    case CLASSIFICATION_NOT_FOUND;

    // Community
    case COMMUNITY_NOT_FOUND;
    case COMMUNITY_INTEREST_EXISTS;
    case WORK_STREAM_NOT_IN_COMMUNITY;
    case WORK_STREAM_NOT_FOUND;
    case DEVELOPMENT_PROGRAM_NOT_VALID_FOR_COMMUNITY;

    // Department
    case DEPARTMENT_NUMBER_IN_USE;
    case DEPARTMENT_NOT_FOUND;
    case DEPARTMENT_MUST_NOT_BE_ARCHIVED;

    // Development Program
    case DEVELOPMENT_PROGRAM_NOT_FOUND;
    case DEVELOPMENT_PROGRAM_COMPLETION_DATE_REQUIRED;
    case DEVELOPMENT_PROGRAM_COMPLETION_DATE_PROHIBITED;

    // Enums
    case ENUM_NOT_FOUND;
    case ENUM_NOT_LOCALIZED;

    // Job poster template
    case ESSENTIAL_SKILL_REQUIRES_LEVEL;
    case NONESSENTIAL_SKILL_PROHIBITS_LEVEL;

    // Notifications
    case CANNOT_ENABLE_NOTIFICATION_FAMILY;

    // Pool
    case CLOSING_DATE_REQUIRED;
    case CLOSING_DATE_FUTURE;
    case LOCATION_REQUIRED;
    case ESSENTIAL_SKILL_REQUIRED;
    case ESSENTIAL_SKILLS_CONTAINS_DELETED;
    case NONESSENTIAL_SKILLS_CONTAINS_DELETED;
    case ENGLISH_KEY_TASKS_REQUIRED;
    case FRENCH_KEY_TASKS_REQUIRED;
    case ENGLISH_YOUR_IMPACT_REQUIRED;
    case FRENCH_YOUR_IMPACT_REQUIRED;
    case ENGLISH_SPECIAL_NOTE_REQUIRED;
    case FRENCH_SPECIAL_NOTE_REQUIRED;
    case POOL_AREA_OF_SELECTION_REQUIRED;
    case CONTACT_EMAIL_REQUIRED;
    case PROCESS_CLOSING_DATE_EXTEND;
    case PROCESS_CLOSING_DATE_FUTURE;
    case CHANGE_JUSTIFICATION_REQUIRED;
    case UNARCHIVE_POOL_INVALID_STATUS;
    case ARCHIVE_POOL_INVALID_STATUS;

    // Pool candidate
    case INVALID_STATUS_DISQUALIFICATION;
    case INVALID_STATUS_PLACING;
    case INVALID_STATUS_QUALIFICATION;
    case INVALID_STATUS_REVERT_FINAL_DECISION;
    case CANDIDATE_NOT_PLACED;
    case CANDIDATE_UNEXPECTED_STATUS;
    case REMOVE_CANDIDATE_ALREADY_PLACED;
    case REMOVE_CANDIDATE_ALREADY_REMOVED;
    case SCREENING_STAGE_REQUIRED;
    case SCREENING_STAGE_EXISTS;
    case SCREENING_STAGE_NOT_UNDER_ASSESSMENT;
    case ASSESSMENT_STEP_PROHIBITED;
    case ASSESSMENT_STEP_CANDIDATE_SAME_POOL;

    // Pool skill
    case POOL_SKILL_NOT_ESSENTIAL_AND_ASSET_TYPES;
    case POOL_SKILL_NOT_VALID;

    // Role
    case TEAM_ID_REQUIRED;
    case TEAM_DOES_NOT_EXIST;
    case ROLE_NOT_TEAM_ROLE;
    case ROLE_NOT_FOUND;

    // Screening question
    case SCREENING_QUESTION_NOT_FOUND;

    // Skill
    case SKILL_NOT_FOUND;

    // Talent event
    case TALENT_EVENT_IS_CLOSED;

    // Talent nominations
    case TALENT_NOMINATION_ALREADY_SUBMITTED;
    case NO_NOMINATIONS_FOR_ADVANCEMENT_TO_DECIDE;
    case NO_NOMINATIONS_FOR_LATERAL_MOVEMENT_TO_DECIDE;
    case NO_NOMINATIONS_FOR_DEVELOPMENT_PROGRAMS_TO_DECIDE;
    case SKILL_NOT_KLC;
    case SKILLS_NOT_ALLOWED_FOR_EVENT;
    case TALENT_NOMINATION_EVENT_NOT_FOUND;
    case NOMINATOR_NOT_FOUND;
    case NOMINATOR_CLASSIFICATION_NOT_FOUND;
    case NOMINATOR_DEPARTMENT_NOT_FOUND;
    case NOMINEE_NOT_FOUND;
    case ADVANCEMENT_REFERENCE_NOT_FOUND;
    case ADVANCEMENT_REFERENCE_CLASSIFICATION_NOT_FOUND;
    case ADVANCEMENT_REFERENCE_DEPARTMENT_NOT_FOUND;

    // User
    case BOTH_STATUS_NON_STATUS;
    case SKILL_USED_ACTIVE_POSTER;
    case FAILED_DUE_SKILL_DELETED;
    case CANNOT_REOPEN_DELETED_SKILL;
    case MISSING_SUBSTANTIVE_EXPERIENCE;
    case TOO_MANY_SUBSTANTIVE_EXPERIENCES;
    case NOT_GOVERNMENT_EMAIL;
    case NOT_VERIFIED_GOVERNMENT_EMPLOYEE;
    case EMAIL_ADDRESS_IN_USE;
    case SUB_IN_USE;
    case VERIFICATION_FAILED;

    // User skill
    case DUPLICATE_USER_SKILL;

    // Work Stream
    case WORK_STREAM_NAME_IN_USE;

    case RATE_LIMIT;

}
