name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr: none
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
variables:
  phpVersion: "8.4"
  serviceConnectionName: "Talent Cloud Service Connection"
  npm_config_user_config: "$(System.DefaultWorkingDirectory)/.npmrc"
  dirResults: "$(System.DefaultWorkingDirectory)/apps/playwright/test-results"
  resourceGroupName: "rg_tbs_talent_2_PaaS"
  vertical: "dev"
  storageAccountName: "sttalclddevcacstdl"
  storageContainer: "playwright-results"
pool:
  name: "TBS Linux Self Hosted"
jobs:
  - job: run_playwright_tests
    displayName: Run Playwright tests
    timeoutInMinutes: 30
    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - task: AzureCLI@2
        displayName: "Update NPMRC Config"
        inputs:
          scriptType: bash
          scriptLocation: inlineScript
          azureSubscription: $(serviceConnectionName)
          inlineScript: |
            NPMRC_FILE="${{ variables.npm_config_user_config }}"
            echo "Editing .npmrc: ${NPMRC_FILE}"
            echo "registry=https://pkgs.dev.azure.com/tbs-sct/53c8b022-82b7-4031-88aa-0d1266fc3bf5/_packaging/TalentCloud_Custom_NPM_Feed/npm/registry/" >> "${NPMRC_FILE}"
      - task: npmAuthenticate@0
        displayName: "00 - NPM Authenticate"
        name: "NPM_Authenticate"
        inputs:
          workingFile: $(npm_config_user_config)

      - script: echo ##vso[task.setvariable variable=NPM_CONFIG_USERCONFIG]$(npm_config_user_config)
        displayName: "Set Custom .npmrc Location"

      - script: pnpm install --no-frozen-lockfile
        displayName: "Install Node.js dependencies"

      - script: pnpm run build
        displayName: "Build dependencies"

      - script: npx playwright install
        displayName: "Install Playwright browsers"

      - script: pnpm run e2e:playwright:chromium
        displayName: "Run playwright tests"
        env:
          CI: "true"
          BASE_URL: "https://dev-talentcloud.tbs-sct.gc.ca"
      - task: AzureCLI@2
        displayName: "Copy Playwright Results to Storage"
        condition: always()
        inputs:
          azureSubscription: $(serviceConnectionName)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            if [ ! $(which az 2> /dev/null) ]; then echo “ERROR: az cli not found” && exit 1; fi
            DIR_SRC="${{ variables.dirResults }}"
            echo "dirResults: ${{ variables.dirResults }}"
            TIMESTAMP="$(date +'%Y-%m-%d %H:%M:%S')"
            echo "Timestamp: ${TIMESTAMP}"
            if [ -d "${DIR_SRC}" ]; then
              SA_RG="${{ variables.resourceGroupName }}"
              SA_NAME="${{ variables.storageAccountName }}"
              SA_CONTAINER_NAME="${{ variables.storageContainer }}"
              SA_CONTAINER_PATH_PREFIX="${{ variables.vertical }}/${TIMESTAMP}"
              AZURE_STORAGE_KEY=$(az storage account keys list --resource-group "$SA_RG" --account-name "$SA_NAME" --query "[0].value" --output tsv)
              az storage blob upload-batch --destination "${SA_CONTAINER_NAME}" --account-name "${SA_NAME}" --destination-path "${SA_CONTAINER_PATH_PREFIX}" --source "${DIR_SRC}"
            else
              echo "No 'test-results' directory found"
            fi
