"""
Builds one self-contained file per page in azure/, with common.py and queries.py inlined,
so a test can be created in the Azure Load Testing portal by uploading a single file.

Usage (from apps/locust, after changing any of the scripts):
  python3 bundle.py
"""

from pathlib import Path

HERE = Path(__file__).parent
PAGES = ["search_page", "browse_jobs_page", "job_poster_page"]

TEMPLATE = '''# Generated by bundle.py from {page}.py, common.py and queries.py. Do not edit by hand.
# Upload this single file as the Locust test script in Azure Load Testing.
import sys
import types


def _module(name, source):
    module = types.ModuleType(name)
    sys.modules[name] = module
    exec(compile(source, name + ".py", "exec"), module.__dict__)
    return module


_module("queries", {queries!r})
_module("common", {common!r})

{page_source}'''


def main():
    out = HERE / "azure"
    out.mkdir(exist_ok=True)
    queries = (HERE / "queries.py").read_text()
    common = (HERE / "common.py").read_text()
    for page in PAGES:
        page_source = (HERE / f"{page}.py").read_text()
        (out / f"{page}.py").write_text(
            TEMPLATE.format(page=page, queries=queries, common=common, page_source=page_source)
        )
        print(f"Wrote azure/{page}.py")


if __name__ == "__main__":
    main()
