// Regenerates queries.py from the frontend codegen output so the load tests
// send the same GraphQL documents the React app sends.
//
// Usage (from the repo root, after `pnpm --filter @gc-digital-talent/graphql codegen`):
//   node apps/locust/generate_queries.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const require = createRequire(join(root, "packages/graphql/package.json"));
const { print, visit, Kind } = require("graphql");

// Operations sent on page load (or on interaction) by the pages under test.
const OPERATIONS = [
  // App shell, sent on every page
  "authorizationQuery",
  "SitewideBanner",
  // Search page
  "SearchForm",
  "SearchRequestOptions",
  "AdvancedFilterOptions",
  "CountTalentRequestMatches",
  // Browse jobs pages
  "OpenJobsPage",
  "ClosedJobsPage",
  // Job poster page
  "PoolAdvertisementPage",
];

const source = readFileSync(
  join(root, "packages/graphql/src/gql/graphql.ts"),
  "utf8",
);

// urql adds __typename to every selection set, so we do too.
const addTypename = (doc) =>
  visit(doc, {
    SelectionSet(node, _key, parent) {
      if (parent?.kind === Kind.OPERATION_DEFINITION) return undefined;
      const hasTypename = node.selections.some(
        (s) => s.kind === Kind.FIELD && s.name.value === "__typename",
      );
      if (hasTypename) return undefined;
      return {
        ...node,
        selections: [
          ...node.selections,
          { kind: Kind.FIELD, name: { kind: Kind.NAME, value: "__typename" } },
        ],
      };
    },
  });

const lines = [
  "# Generated by generate_queries.mjs from the frontend codegen output. Do not edit by hand.",
  "# fmt: off",
  "",
];
for (const name of OPERATIONS) {
  const match = source.match(
    new RegExp(
      `export const ${name[0].toUpperCase()}${name.slice(1)}Document = (\\{.*?\\}) as unknown as DocumentNode`,
      "s",
    ),
  );
  if (!match) throw new Error(`Missing document for ${name}`);
  const printed = print(addTypename(JSON.parse(match[1])));
  lines.push(`${name} = """\n${printed}\n"""`, "");
}

writeFileSync(join(here, "queries.py"), lines.join("\n"));
console.log(`Wrote ${OPERATIONS.length} operations to queries.py`);
