# Generated by generate_queries.mjs from the frontend codegen output. Do not edit by hand.
# fmt: off

authorizationQuery = """
query authorizationQuery {
  myAuth {
    id
    deletedDate
    roleAssignments {
      id
      role {
        id
        name
        isTeamBased
        permissions
        displayName {
          en
          fr
          __typename
        }
        __typename
      }
      team {
        id
        name
        __typename
      }
      __typename
    }
    __typename
  }
}
"""

SitewideBanner = """
query SitewideBanner {
  sitewideAnnouncement {
    isEnabled
    isDismissible
    publishDate
    expiryDate
    title {
      en
      fr
      __typename
    }
    message {
      en
      fr
      __typename
    }
    updatedAt
    __typename
  }
}
"""

SearchForm = """
query SearchForm {
  classifications(availableInSearch: true) {
    id
    group
    level
    name {
      localized
      __typename
    }
    groupAndLevel
    displayName
    __typename
  }
  workStreams(talentSearchable: true) {
    id
    name {
      localized
      __typename
    }
    __typename
  }
  skills {
    ...SkillBrowserSkill
    id
    key
    name {
      en
      fr
      __typename
    }
    category {
      value
      label {
        en
        fr
        __typename
      }
      __typename
    }
    description {
      en
      fr
      __typename
    }
    keywords {
      en
      fr
      __typename
    }
    families {
      id
      key
      name {
        en
        fr
        __typename
      }
      __typename
    }
    __typename
  }
}

fragment SkillBrowserSkill on Skill {
  id
  name {
    localized
    __typename
  }
  description {
    localized
    __typename
  }
  category {
    value
    __typename
  }
  families {
    id
    name {
      localized
      __typename
    }
    __typename
  }
  __typename
}
"""

SearchRequestOptions = """
query SearchRequestOptions {
  languageAbilities: localizedEnumStrings(enumName: "LanguageAbility") {
    value
    label {
      en
      fr
      __typename
    }
    __typename
  }
  workRegions: localizedEnumStrings(enumName: "WorkRegion") {
    value
    label {
      en
      fr
      __typename
    }
    __typename
  }
  flexibleWorkLocations: localizedEnumStrings(enumName: "FlexibleWorkLocation") {
    value
    label {
      localized
      __typename
    }
    __typename
  }
  talentSources: localizedEnumOptions(enumName: "TalentRequestSource") {
    ... on LocalizedTalentRequestSource {
      value
      label {
        localized
        __typename
      }
      __typename
    }
    __typename
  }
}
"""

AdvancedFilterOptions = """
query AdvancedFilterOptions {
  operationalRequirements: localizedEnumStrings(
    enumName: "OperationalRequirement"
  ) {
    value
    label {
      en
      fr
      __typename
    }
    __typename
  }
}
"""

CountTalentRequestMatches = """
query CountTalentRequestMatches($where: TalentRequestMatchFilterInput) {
  countTalentRequestMatches(where: $where)
  countTalentRequestMatchesByPool(where: $where) {
    pool {
      id
      ...SearchResultCard_Pool
      __typename
    }
    count
    __typename
  }
  countTalentRequestMatchesByCommunity(where: $where) {
    community {
      id
      name {
        localized
        __typename
      }
      __typename
    }
    qualifiedInPoolCount
    atLevelCount
    count
    __typename
  }
}

fragment SearchResultCard_Pool on Pool {
  id
  workStream {
    id
    name {
      en
      fr
      __typename
    }
    __typename
  }
  classification {
    groupAndLevel
    __typename
  }
  name {
    en
    fr
    __typename
  }
  community {
    id
    name {
      localized
      __typename
    }
    __typename
  }
  poolSkills(type: ESSENTIAL) {
    id
    type {
      value
      label {
        en
        fr
        __typename
      }
      __typename
    }
    skill {
      id
      name {
        en
        fr
        __typename
      }
      description {
        en
        fr
        __typename
      }
      category {
        value
        label {
          en
          fr
          __typename
        }
        __typename
      }
      key
      __typename
    }
    __typename
  }
  __typename
}
"""

OpenJobsPage = """
query OpenJobsPage {
  poolsPaginated(
    where: {statuses: [PUBLISHED], isHidden: false}
    first: 500
    orderBy: {column: "closing_date", order: ASC}
  ) {
    data {
      id
      status {
        value
        label {
          en
          fr
          __typename
        }
        __typename
      }
      ...ActiveRecruitmentSectionPool
      __typename
    }
    __typename
  }
}

fragment JobCard on Pool {
  id
  department {
    name {
      localized
      __typename
    }
    __typename
  }
  workStream {
    id
    name {
      en
      fr
      __typename
    }
    __typename
  }
  closingDate
  name {
    en
    fr
    __typename
  }
  classification {
    id
    groupAndLevel
    minSalary
    maxSalary
    __typename
  }
  poolSkills {
    id
    type {
      value
      label {
        en
        fr
        __typename
      }
      __typename
    }
    skill {
      id
      category {
        value
        label {
          en
          fr
          __typename
        }
        __typename
      }
      key
      name {
        en
        fr
        __typename
      }
      __typename
    }
    __typename
  }
  areaOfSelection {
    value
    __typename
  }
  selectionLimitations {
    value
    __typename
  }
  isRemote
  location {
    localized
    __typename
  }
  language {
    value
    label {
      localized
      __typename
    }
    __typename
  }
  publishedAt
  applicantsCount
  __typename
}

fragment ActiveRecruitmentSectionPool on Pool {
  id
  closingDate
  publishedAt
  ...JobCard
  __typename
}
"""

ClosedJobsPage = """
query ClosedJobsPage {
  poolsPaginated(
    where: {statuses: [CLOSED], isHidden: false}
    first: 500
    orderBy: {column: "closing_date", order: DESC}
  ) {
    data {
      id
      status {
        value
        label {
          en
          fr
          __typename
        }
        __typename
      }
      ...ClosedJobOpportunitiesSectionPool
      __typename
    }
    __typename
  }
}

fragment JobCard on Pool {
  id
  department {
    name {
      localized
      __typename
    }
    __typename
  }
  workStream {
    id
    name {
      en
      fr
      __typename
    }
    __typename
  }
  closingDate
  name {
    en
    fr
    __typename
  }
  classification {
    id
    groupAndLevel
    minSalary
    maxSalary
    __typename
  }
  poolSkills {
    id
    type {
      value
      label {
        en
        fr
        __typename
      }
      __typename
    }
    skill {
      id
      category {
        value
        label {
          en
          fr
          __typename
        }
        __typename
      }
      key
      name {
        en
        fr
        __typename
      }
      __typename
    }
    __typename
  }
  areaOfSelection {
    value
    __typename
  }
  selectionLimitations {
    value
    __typename
  }
  isRemote
  location {
    localized
    __typename
  }
  language {
    value
    label {
      localized
      __typename
    }
    __typename
  }
  publishedAt
  applicantsCount
  __typename
}

fragment ClosedJobOpportunitiesSectionPool on Pool {
  id
  closingDate
  publishedAt
  ...JobCard
  __typename
}
"""

PoolAdvertisementPage = """
query PoolAdvertisementPage($id: UUID!) {
  me {
    id
    poolCandidates {
      id
      pool {
        id
        __typename
      }
      submittedAt
      __typename
    }
    __typename
  }
  pool(id: $id) {
    ...PoolAdvertisement
    id
    status {
      value
      __typename
    }
    __typename
  }
}

fragment GenericJobTitleAccordion on GenericJobTitle {
  id
  key
  name {
    localized
    __typename
  }
  __typename
}

fragment PoolSkillAccordion on PoolSkill {
  id
  requiredLevel
  skill {
    id
    key
    category {
      value
      __typename
    }
    name {
      en
      fr
      __typename
    }
    description {
      en
      fr
      __typename
    }
    __typename
  }
  __typename
}

fragment AreaOfSelectionNote on Pool {
  classification {
    groupAndLevel
    __typename
  }
  department {
    name {
      en
      fr
      __typename
    }
    __typename
  }
  areaOfSelection {
    value
    __typename
  }
  selectionLimitations {
    value
    __typename
  }
  __typename
}

fragment WhoCanApplyText on Pool {
  classification {
    groupAndLevel
    __typename
  }
  department {
    name {
      en
      fr
      __typename
    }
    __typename
  }
  areaOfSelection {
    value
    __typename
  }
  selectionLimitations {
    value
    __typename
  }
  __typename
}

fragment PoolAdvertisement on Pool {
  id
  name {
    en
    fr
    __typename
  }
  workStream {
    id
    name {
      en
      fr
      __typename
    }
    __typename
  }
  closingDate
  wasClosedEarly
  status {
    value
    label {
      en
      fr
      __typename
    }
    __typename
  }
  language {
    value
    label {
      en
      fr
      __typename
    }
    __typename
  }
  securityClearance {
    value
    label {
      en
      fr
      __typename
    }
    __typename
  }
  department {
    name {
      en
      fr
      __typename
    }
    __typename
  }
  opportunityLength {
    value
    label {
      en
      fr
      __typename
    }
    __typename
  }
  classification {
    id
    group
    groupAndLevel
    minSalary
    maxSalary
    genericJobTitles {
      id
      ...GenericJobTitleAccordion
      __typename
    }
    __typename
  }
  yourImpact {
    en
    fr
    __typename
  }
  keyTasks {
    en
    fr
    __typename
  }
  whatToExpect {
    en
    fr
    __typename
  }
  specialNote {
    en
    fr
    __typename
  }
  whatToExpectAdmission {
    en
    fr
    __typename
  }
  aboutUs {
    en
    fr
    __typename
  }
  poolSkills {
    id
    type {
      value
      label {
        en
        fr
        __typename
      }
      __typename
    }
    skill {
      id
      key
      category {
        value
        label {
          en
          fr
          __typename
        }
        __typename
      }
      name {
        en
        fr
        __typename
      }
      __typename
    }
    ...PoolSkillAccordion
    __typename
  }
  isRemote
  location {
    en
    fr
    __typename
  }
  workStream {
    id
    name {
      en
      fr
      __typename
    }
    __typename
  }
  processNumber
  community {
    key
    __typename
  }
  contactEmail
  ...AreaOfSelectionNote
  ...WhoCanApplyText
  __typename
}
"""
