# Changes to workflow name require changes to badge URL in README.md
name: Docker Smoke Test

on:
  push:

jobs:
  cypress-run:
    # Platform recommended in cypress-io/github-action docs.
    runs-on: ubuntu-20.04
    env:
      # Use native docker command within docker-compose
      COMPOSE_DOCKER_CLI_BUILD: 1
      # Use buildkit to speed up docker command
      DOCKER_BUILDKIT: 1
    defaults:
      run:
        working-directory: infrastructure
    steps:
      # This ensures only the most recently push commit will keep running.
      - name: Cancel other active runs of this workflow
        uses: rokroskar/workflow-run-cleanup-action@v0.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Serve app via docker-compose
        run: docker-compose up --detach

      - name: "Confirm non-200 response"
        run: curl http://localhost:8000/talent --output /dev/null --silent --write-out "%{http_code}"  | grep --invert-match 200

      - name: "Run: setup.sh"
        run: docker-compose run --rm maintenance bash setup.sh

      - name: "Confirm success response: setup.sh"
        run: |
          curl --silent http://localhost:8000/talent | grep /talent/app.js
          curl --silent http://localhost:8000/admin | grep /admin/app.js
          curl --silent http://localhost:8000/indigenous-it-apprentice | grep /indigenous-it-apprentice/app.js
          curl --silent http://localhost:8000/en/talent-cloud | grep "GC Talent | Talent Cloud"

      - name: "Run: refresh_all.sh"
        run: docker-compose run --rm maintenance bash refresh_all.sh

      - name: "Confirm success response: refresh_all.sh"
        run: |
          curl --silent http://localhost:8000/talent | grep /talent/app.js
          curl --silent http://localhost:8000/admin | grep /admin/app.js
          curl --silent http://localhost:8000/indigenous-it-apprentice | grep /indigenous-it-apprentice/app.js
          curl --silent http://localhost:8000/en/talent-cloud | grep "GC Talent | Talent Cloud"
