# Changes to workflow name require changes to badge URL in README.md
name: Docker Smoke Test

on:
  push:

jobs:
  cypress-run:
    # Platform recommended in cypress-io/github-action docs.
    runs-on: ubuntu-20.04
    env:
      # Use native docker command within docker-compose
      COMPOSE_DOCKER_CLI_BUILD: 1
      # Use buildkit to speed up docker command
      DOCKER_BUILDKIT: 1
    steps:
      # This ensures only the most recently push commit will keep running.
      - name: Cancel other active runs of this workflow
        uses: rokroskar/workflow-run-cleanup-action@v0.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Serve app via docker-compose
        working-directory: infrastructure
        run: docker-compose up --detach

      - name: Run setup.sh
        working-directory: infrastructure
        run: docker-compose run --rm maintenance bash setup.sh

      - name: Run refresh_all.sh
        working-directory: infrastructure
        run: docker-compose run --rm maintenance bash refresh_all.sh
