# Changes to workflow name require changes to badge URL in README.md
name: Docker Smoke Test

on:
  push:

jobs:
  cypress-run:
    # Platform recommended in cypress-io/github-action docs.
    runs-on: ubuntu-20.04
    env:
      # Use native docker command within docker-compose
      COMPOSE_DOCKER_CLI_BUILD: 1
      # Use buildkit to speed up docker command
      DOCKER_BUILDKIT: 1
    steps:
      # This ensures only the most recently push commit will keep running.
      - name: Cancel other active runs of this workflow
        uses: rokroskar/workflow-run-cleanup-action@v0.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      # This uses GitHub Action cache for docker container layers
      # See: https://github.com/marketplace/actions/docker-layer-caching
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore a failure of this step and avoid terminating the job.
        continue-on-error: true
        # By default, this cache is keyed to the workflow name. Consider
        # setting a shared key if you'd like the docker cache to be shared
        # across multiple workflows. (uncomment below)
        #
        #with:
        #  key: some-shared-key-{hash}
        #  restore-keys: |
        #  some-shared-key-

      - name: Serve app via docker-compose
        working-directory: infrastructure/
        run: docker-compose up --detach

      - name: "Confirm failure response"
        # Match any non-200 HTTP response code (301 or 404)
        run: |
          curl http://localhost:8000/talent --output /dev/null --silent --write-out "%{http_code}"  | grep --invert-match 200

      - name: "Run: setup.sh"
        working-directory: infrastructure/
        run: docker-compose run --rm maintenance bash setup.sh

      - name: "Confirm success response: setup.sh"
        run: |
          curl --silent http://localhost:8000/talent | grep /talent/app.js
          curl --silent http://localhost:8000/admin | grep /admin/app.js
          curl --silent http://localhost:8000/indigenous-it-apprentice | grep /indigenous-it-apprentice/app.js
          curl --silent http://localhost:8000/en/talent-cloud | grep "GC Talent | Talent Cloud"

      - name: Break web apps
        run: rm frontend/*/dist/index.html

      - name: "Confirm failure response"
        # Match any non-200 HTTP response code (301 or 404)
        run: |
          curl http://localhost:8000/talent --output /dev/null --silent --write-out "%{http_code}"  | grep --invert-match 200

      - name: "Run: refresh_all.sh"
        working-directory: infrastructure/
        run: docker-compose run --rm maintenance bash refresh_all.sh

      - name: "Confirm success response: refresh_all.sh"
        run: |
          curl --silent http://localhost:8000/talent | grep /talent/app.js
          curl --silent http://localhost:8000/admin | grep /admin/app.js
          curl --silent http://localhost:8000/indigenous-it-apprentice | grep /indigenous-it-apprentice/app.js
          curl --silent http://localhost:8000/en/talent-cloud | grep "GC Talent | Talent Cloud"
